services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-8000}:8000'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      API_DOLLAR_URL: '${API_DOLLAR_URL}'
      DB_HOST: ${DB_HOST}
      DB_CONNECTION: pgsql
      DB_PORT: ${DB_PORT:-secret}
      DB_DATABASE: ${DB_DATABASE:-secret}
      DB_USERNAME: ${DB_USERNAME:-secret}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - pgsql
  pgsql:
    image: 'postgres:15'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
  sail-pgsql:
    driver: local
